title: "TEST HOME" 
description: "HOME..." 
# highlighter: rouge
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'language-'
    span:
      line_numbers: false
    block:
      line_numbers: false
